    pipeline {
    agent any
    environment {
        RELEASE='20.04'
    }
    stages {    
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }        
    }
    post{
        always {
             echo 'Prints whether deploy happened or not, success or failure'

             emailext body: '''Build Status :

            Build Number - $BUILD_NUMBER : and the status is : $BUILD_STATUS''', recipientProviders: [developers()], subject: 'Build Status', to: 'saurabh.d2106@gmail.com'
        }
    }
}