pipeline {
   agent any
   
   environment {
       DEMO='1.1'
   }

   stages {
      stage('stage-1') {
         steps {
            
            echo "This is my first Jenkins Pipeline with $BUILD_NUMBER and $DEMO"

            sh "echo \"This is my first Jenkins Pipeline with $BUILD_NUMBER and $DEMO\""
            
         }
      }
   }
}